/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metromendeley;

/**
 *
 * @author andresimery
 */
public class Ventana2 extends javax.swing.JFrame {

    public static Ventana1 v1;
    public static HashTable hash;
    public static Articulo[] articulos;
    public static int currentArticle;
    
    /**
     * Creates new form Ventana2
     */
    public Ventana2(Ventana1 v1, HashTable hash) {
        initComponents();
        this.v1 = v1;
        this.hash = hash;
        this.articulos = hash.mostrarTodos();
        this.currentArticle = 0;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
//        this.jTextAreaArticulo.append(hash.buscarArticuloPorTitulo("Complemento de software para el diseño de fundaciones.").stringArticle());
        this.jTextAreaArticulo.append(articulos[0].stringArticle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArticulo = new javax.swing.JTextArea();
        jButtonMainMenu = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaArticulo.setEditable(false);
        jTextAreaArticulo.setColumns(20);
        jTextAreaArticulo.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jTextAreaArticulo.setLineWrap(true);
        jTextAreaArticulo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaArticulo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 460));

        jButtonMainMenu.setText("Main Menu");
        jButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMenuActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_jButtonMainMenuActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        this.jTextAreaArticulo.setText("");
        try {
            this.jTextAreaArticulo.append(articulos[currentArticle + 1].stringArticle());
            currentArticle = currentArticle + 1;
        } catch (Exception e) {
            this.jTextAreaArticulo.append(articulos[currentArticle].stringArticle());
        }
        
        
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.jTextAreaArticulo.setText("");
        try {
            this.jTextAreaArticulo.append(articulos[currentArticle - 1].stringArticle());
            currentArticle = currentArticle - 1;
        } catch (Exception e) {
            this.jTextAreaArticulo.append(articulos[currentArticle].stringArticle());
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1, hash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonMainMenu;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArticulo;
    // End of variables declaration//GEN-END:variables
}
