/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metromendeley;

import javax.swing.JOptionPane;

/**
 *
 * @author andresimery
 */
public class Ventana3 extends javax.swing.JFrame {

    public static HashTable hash;
    public static Ventana1 v1;
    
    /**
     * Creates new form Ventana3
     */
    public Ventana3(Ventana1 v1, HashTable hash) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.hash = hash;
        this.v1 = v1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldBuscar = new java.awt.TextField();
        jButtonBuscarTitulo = new javax.swing.JButton();
        jButtonBuscarAutor = new javax.swing.JButton();
        jButtonBuscarPalabraClave = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(textFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 430, -1));

        jButtonBuscarTitulo.setText("Buscar por Titulo");
        jButtonBuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, -1));

        jButtonBuscarAutor.setText("Buscar por Autor");
        jButtonBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, -1));

        jButtonBuscarPalabraClave.setText("Buscar por Palabra Clave");
        jButtonBuscarPalabraClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPalabraClaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, -1));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarTituloActionPerformed
        String titulo = this.textFieldBuscar.getText();
        Articulo articulo = hash.buscarArticuloPorTitulo(titulo);
        if (articulo != null) {
            new Ventana4(this, articulo);
        } else {
            JOptionPane.showMessageDialog(null, "No existe ningún artículo con ese título");
        }
        
    }//GEN-LAST:event_jButtonBuscarTituloActionPerformed

    private void jButtonBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAutorActionPerformed
        String autor = this.textFieldBuscar.getText();
        Articulo articulo = hash.buscarArticuloPorAutor(autor);
        if (articulo != null) {
            new Ventana4(this, articulo);
        } else {
            JOptionPane.showMessageDialog(null, "No existe ningún artículo con ese autor");
        }
    }//GEN-LAST:event_jButtonBuscarAutorActionPerformed

    private void jButtonBuscarPalabraClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPalabraClaveActionPerformed
        String palabra_clave = this.textFieldBuscar.getText();
        Articulo articulo = hash.buscarArticuloPorPalabraClave(palabra_clave);
        if (articulo != null) {
            new Ventana4(this, articulo);
        } else {
            JOptionPane.showMessageDialog(null, "No existe ningún artículo con esa palabra clave");
        }
    }//GEN-LAST:event_jButtonBuscarPalabraClaveActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(v1, hash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBuscarAutor;
    private javax.swing.JButton jButtonBuscarPalabraClave;
    private javax.swing.JButton jButtonBuscarTitulo;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField textFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
